export { BadGatewayRestError, BadGatewayRestError as BadGateway }  from './src/classes/bad-gateway-rest-error';
export { BadRequestRestError, BadRequestRestError as BadRequest }  from './src/classes/bad-request-rest-error';
export { ConflictRestError, ConflictRestError as Conflict }  from './src/classes/conflict-rest-error';
export { ExpectationFailedRestError, ExpectationFailedRestError as ExpectationFailed }  from './src/classes/expectation-failed-rest-error';
export { ForbiddenRestError, ForbiddenRestError as Forbidden }  from './src/classes/forbidden-rest-error';
export { GatewayTimeOutRestError, GatewayTimeOutRestError as GatewayTimeOut }  from './src/classes/gateway-time-out-rest-error';
export { GoneRestError, GoneRestError as Gone }  from './src/classes/gone-rest-error';
export { HTTPVersionNotSupportedRestError, HTTPVersionNotSupportedRestError as HTTPVersionNotSupported }  from './src/classes/http-version-not-supported-rest-error';
export { InternalServerErrorRestError, InternalServerErrorRestError as InternalServerError }  from './src/classes/internal-server-error-rest-error';
export { LengthRequiredRestError, LengthRequiredRestError as LengthRequired }  from './src/classes/length-required-rest-error';
export { MethodNotAllowedRestError, MethodNotAllowedRestError as MethodNotAllowed }  from './src/classes/method-not-allowed-rest-error';
export { NotAcceptableRestError, NotAcceptableRestError as NotAcceptable }  from './src/classes/not-acceptable-rest-error';
export { NotFoundRestError, NotFoundRestError as NotFound }  from './src/classes/not-found-rest-error';
export { NotImplementedRestError, NotImplementedRestError as NotImplemented }  from './src/classes/not-implemented-rest-error';
export { PaymentRequiredRestError, PaymentRequiredRestError as PaymentRequired }  from './src/classes/payment-required-rest-error';
export { PreconditionFailedRestError, PreconditionFailedRestError as PreconditionFailed }  from './src/classes/precondition-failed-rest-error';
export { ProxyAuthenticationRequiredRestError, ProxyAuthenticationRequiredRestError as ProxyAuthenticationRequired }  from './src/classes/proxy-authentication-required-rest-error';
export { RequestEntityTooLargeRestError, RequestEntityTooLargeRestError as RequestEntityTooLarge }  from './src/classes/request-entity-too-large-rest-error';
export { RequestRangeUnsatisfiableRestError, RequestRangeUnsatisfiableRestError as RequestRangeUnsatisfiable }  from './src/classes/request-range-unsatisfiable-rest-error';
export { RequestTimeOutRestError, RequestTimeOutRestError as RequestTimeOut }  from './src/classes/request-time-out-rest-error';
export { RequestUriTooLongRestError, RequestUriTooLongRestError as RequestUriTooLong }  from './src/classes/request-uri-too-long-rest-error';
export { RestError } from './src/classes/rest-error';
export { ServiceUnavailableRestError, ServiceUnavailableRestError as ServiceUnavailable }  from './src/classes/service-unavailable-rest-error';
export { UnauthorizedRestError, UnauthorizedRestError as Unauthorized }  from './src/classes/unauthorized-rest-error';
export { UnsupportedMediaTypeRestError, UnsupportedMediaTypeRestError as UnsupportedMediaType }  from './src/classes/unsupported-media-type-rest-error';
export { IRestError } from './src/interfaces/rest-error';
export { isRestError } from './src/utils/is-rest-error';
export { fromStatusCode } from './src/utils/from-status-code';
export { TRestErrorMeta } from './src/types/rest-error-meta';
export { TRestErrorCode } from './src/types/rest-error-code';