export { BadGatewayRestError, BadGatewayRestError as BadGateway }  from './src/classes';
export { BadRequestRestError, BadRequestRestError as BadRequest }  from './src/classes';
export { ConflictRestError, ConflictRestError as Conflict }  from './src/classes';
export { ExpectationFailedRestError, ExpectationFailedRestError as ExpectationFailed }  from './src/classes';
export { ForbiddenRestError, ForbiddenRestError as Forbidden }  from './src/classes';
export { GatewayTimeOutRestError, GatewayTimeOutRestError as GatewayTimeOut }  from './src/classes';
export { GoneRestError, GoneRestError as Gone }  from './src/classes';
export { HTTPVersionNotSupportedRestError, HTTPVersionNotSupportedRestError as HTTPVersionNotSupported }  from './src/classes';
export { InternalServerErrorRestError, InternalServerErrorRestError as InternalServerError }  from './src/classes';
export { LengthRequiredRestError, LengthRequiredRestError as LengthRequired }  from './src/classes';
export { MethodNotAllowedRestError, MethodNotAllowedRestError as MethodNotAllowed }  from './src/classes';
export { NotAcceptableRestError, NotAcceptableRestError as NotAcceptable }  from './src/classes';
export { NotFoundRestError, NotFoundRestError as NotFound }  from './src/classes';
export { NotImplementedRestError, NotImplementedRestError as NotImplemented }  from './src/classes';
export { PaymentRequiredRestError, PaymentRequiredRestError as PaymentRequired }  from './src/classes';
export { PreconditionFailedRestError, PreconditionFailedRestError as PreconditionFailed }  from './src/classes';
export { ProxyAuthenticationRequiredRestError, ProxyAuthenticationRequiredRestError as ProxyAuthenticationRequired }  from './src/classes';
export { RequestEntityTooLargeRestError, RequestEntityTooLargeRestError as RequestEntityTooLarge }  from './src/classes';
export { RequestRangeUnsatisfiableRestError, RequestRangeUnsatisfiableRestError as RequestRangeUnsatisfiable }  from './src/classes';
export { RequestTimeOutRestError, RequestTimeOutRestError as RequestTimeOut }  from './src/classes';
export { RequestUriTooLongRestError, RequestUriTooLongRestError as RequestUriTooLong }  from './src/classes';
export { RestError } from './src/classes';
export { ServiceUnavailableRestError, ServiceUnavailableRestError as ServiceUnavailable }  from './src/classes';
export { UnauthorizedRestError, UnauthorizedRestError as Unauthorized }  from './src/classes';
export { UnsupportedMediaTypeRestError, UnsupportedMediaTypeRestError as UnsupportedMediaType }  from './src/classes';
export { IRestError } from './src/interfaces/rest-error';
export { isRestError } from './src/utils/is-rest-error';
export { fromStatusCode } from './src/utils/from-status-code';
export { TRestErrorMeta } from './src/types/rest-error-meta';
export { TRestErrorCode } from './src/types/rest-error-code';